name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

  flutter_svg: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/digital_marketing_agency_ntwrk_g_39_p_1_kdjv_sy_unsplash_1.jpeg
  - assets/images/avi_werde_hhz_4_yrvxwl_aunsplash_1.jpeg
  - assets/images/pexels_expect_best_3237801.jpeg
  - assets/images/rarchitecture_kqpeh_ywe_lr_qunsplash_1.jpeg
  - assets/images/webaliser_tptxzd_9_moo_unsplash_1.jpeg
  - assets/images/ksenia_balandina_rcf_5_kswb_7_ms_unsplash_1.jpeg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/group_14_x2.svg
  - assets/vectors/vector_67_x2.svg
  - assets/vectors/vector_64_x2.svg
  - assets/vectors/ic_notification_5_x2.svg
  - assets/vectors/vector_65_x2.svg
  - assets/vectors/vector_56_x2.svg
  - assets/vectors/group_16_x2.svg
  - assets/vectors/group_18_x2.svg
  - assets/vectors/group_13_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_63_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/images/jason_briscoe_uv_81_e_0_oxxwq_unsplash_1.jpeg
  - assets/images/maps.png
  - assets/images/jurica_koletic_7_yvzyze_itc_8_unsplash_adobespark_1.png
  - assets/images/sidekix_media_eo_tucbv_9_jrs_unsplash_1.jpeg
  - assets/images/jorge_de_jorge_nvq_yk_dpe_0_rw_unsplash_1.jpeg
  - assets/images/webaliser_tptxzd_9_moo_unsplash_1.jpeg
  - assets/images/cat_han_apd_1_ynuyp_0_wunsplash_1.jpeg
  - assets/vectors/vector_66_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/group_117_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/vector_72_x2.svg
  - assets/images/detail_produk_13.png
  - assets/images/detail_produk.png
  - assets/images/menu.png
  - assets/images/home_screen.png
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/vector_68_x2.svg
  - assets/images/menu.png
  - assets/images/home_screen.png
  - assets/images/detail_produk_13.png
  - assets/images/menu.png
  - assets/images/detail_produk_13.png
  - assets/images/img_201912070908401.jpeg
  - assets/images/detail_produk.png
  - assets/images/home_screen.png
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/vector_74_x2.svg
  - assets/images/detail_produk_13.png
  - assets/images/menu.png
  - assets/images/img_201912070908401.jpeg
  - assets/images/home_screen.png
  - assets/images/img_201912070908401.jpeg
  - assets/vectors/group_35_x2.svg
  - assets/images/home_screen.png
  - assets/images/detail_produk.png
  - assets/images/menu.png
  - assets/images/detail_produk_13.png
  - assets/vectors/vector_76_x2.svg
  - assets/vectors/vector_69_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/images/jorge_de_jorge_nvq_yk_dpe_0_rw_unsplash_1.jpeg
  - assets/images/rarchitecture_kqpeh_ywe_lr_qunsplash_1.jpeg
  - assets/images/cat_han_apd_1_ynuyp_0_wunsplash_1.jpeg
  - assets/images/sidekix_media_eo_tucbv_9_jrs_unsplash_1.jpeg
  - assets/images/jason_briscoe_uv_81_e_0_oxxwq_unsplash_1.jpeg
  - assets/images/jurica_koletic_7_yvzyze_itc_8_unsplash_adobespark_1.png
  - assets/images/digital_marketing_agency_ntwrk_g_39_p_1_kdjv_sy_unsplash_1.jpeg
  - assets/images/ksenia_balandina_rcf_5_kswb_7_ms_unsplash_1.jpeg
  - assets/images/avi_werde_hhz_4_yrvxwl_aunsplash_1.jpeg
  - assets/images/maps.png
  - assets/images/webaliser_tptxzd_9_moo_unsplash_1.jpeg
  - assets/images/pexels_expect_best_3237801.jpeg
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/ic_notification_1_x2.svg
  - assets/vectors/vector_75_x2.svg
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/ic_message_x2.svg
  - assets/vectors/group_116_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/vector_55_x2.svg
  - assets/vectors/group_110_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/ic_notification_4_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/group_12_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/group_15_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/ic_notification_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/group_112_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/vectors/group_113_x2.svg
  - assets/vectors/group_11_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/vector_52_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/vectors/group_19_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/images/detail_produk_13.png
  - assets/images/menu.png
  - assets/images/home_screen.png
  - assets/images/pexels_expect_best_3237801.jpeg
  - assets/images/avi_werde_hhz_4_yrvxwl_aunsplash_1.jpeg
  - assets/images/rarchitecture_kqpeh_ywe_lr_qunsplash_1.jpeg
  - assets/images/digital_marketing_agency_ntwrk_g_39_p_1_kdjv_sy_unsplash_1.jpeg
  - assets/images/ksenia_balandina_rcf_5_kswb_7_ms_unsplash_1.jpeg
  - assets/images/webaliser_tptxzd_9_moo_unsplash_1.jpeg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/group_17_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/group_114_x2.svg
  - assets/vectors/vector_73_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_54_x2.svg
  - assets/vectors/vector_70_x2.svg
  - assets/vectors/group_115_x2.svg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/vector_77_x2.svg
  - assets/vectors/group_111_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/ic_notification_3_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/ic_notification_2_x2.svg
  - assets/vectors/ic_message_1_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/vector_30_x2.svg

